appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: k2p0gjO3i8/j1JDuuHf6QqDOSbBbr2bh+GI06vJeJD6PdTugsZgPylEy5oqR534qqFOt19xiU8ehqCjzdNcQWvWdb4FYChQJXRyQwBSURBeoR5wcTzvTsaylHTSG+DR73M6+xCWvYQo6KHkKl0QRkNJUX/vgW8HMmVlPhKvNIfkHnKqacFjA4bxcOsiipfXz3VIpdKgRqaWojBUF46dUSUzibt3LeKvaXlnwFgy/Cts2G9n3bt486pmj2zok3y8kaSVRhlpWCggdRSDdHTLIHv51LmaMpelQnDkSmfAkJ1ed8eiEILHwnp8g8HWM6DCRI78s1f9L+iAX1oi+rnMKtDaN1lZfAkZcTCODRu3IZjiuZ/vmpqC3yDpk5QFutascfIUKesRJJtzWeZTDel1kinkn1SmIznP/Jxmh9/8JzCY0SI7NOdlP26A1l4cmifR62fW7/1gRR5phts+2JMClPTNHPOOrqVbF5MGPLS0kKuumlEPPeR5IslZ7CnoMUq5LzDExeHXeq6S65s/hHm2T3jacK9Lxsqj6tjJvEo+7PH0PPjLJbLWVmqjCcrGbYYaxkRJg0k7EmmErMUdZeugVQAjJnNL/9eZqRwOPVG7mvAZPm+TLByZ4lK2aQ7fL1vJndR4lVXsEY2v/Uvl2I59zAJZso4Sp6WtEihKEEzkLhcU=
conda_forge_output_validation: true
