travis:
  secure:
    BINSTAR_TOKEN: fxxnlSxAHTRVhuFpOcHDMD9VOs7UnmAjJzzQM9dySKkfo96MW995JHemC5PjSoLEhd/6lvLnGRdApLJ4F9NStqJ/fchxwmacNXVO8y7LsBbjBnNtuxd3peKP6BCmxUTBWUhLa0HlhLFsMwjGK+RWGZpdmSkvYzVNCbPH6igobnipB2AE9BMUa0FrTbC90+fZ9mGILOCuMtbiQNf3MzNOUeSKTGWs3hxvoTtvuAAV1u1gTLRupXkJfgFlZAjuYbCr8s++6A8gjIhxQE+n/ZktBmLoUJAu6CRfliCaxMwlqTbL+2wPIlPVPbaTdDQ8LF7lZCQp2F9lXfrHGQX/Ne2SJ0iJKNe5lpv4GCJoFudhySpyEcgYzoCw2tq071bYq0fgvJK4G/do0bsxNY8R46XSkDKons852rF2w158+KhSxpDxRIy7UtGGl9PUpRvUxws9ZnGP3rTtbTKCt7TENEq26p+wBLfloj/sDYRrDi39j6ZtZSdouz8CW5NTJ8VpQuHZSvfsMvo7MNOQPqqdNANJkMIqALdMDXRAaBxpc+7TM8FLrkVI0klcpL4IYhA3k7rt/2UiXS1rta9ge9vS7CyV1X15jI5iJa3UfJvq7+VV0HbdFQgTccbP4hKl4Y3Bsx/jb+UShY+/y/assAOu5ssOw6IM3ND2JwjSbbdglCBTWZM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
